"""Auto-generated type stub for IDE support - DO NOT EDIT MANUALLY"""
# Generated by: python -m geovocab2.tools.generate_stubs

from .factory_base import FactoryBase

from .factory_dataloader import (
    TensorFactory,
)
from .legacy_factory import (
    LegacyFactory,
)
from .simplex_factory import (
    SimplexFactory,
)

__all__: list[str]
